language: javascript
node_js:
  - 12.7
stages:
  - lint
  - test
jobs:
  include:
    - stage: lint
      script: npm run eslint
      script: npm run flow
    - stage: test
      script: npm run test
